---
title: "seurat_scenic_python"
author: "Sanketh"
date: "2024-01-07"
output: html_document
---

```{r setup, include=FALSE}

```

```{r}
rm(list=ls())
library(tidyverse)
library(Seurat)
library(ggplot2)
library(stringr)
#install.packages("Matrix")
#library(Matrix)
library(scCustomize)
library(harmony)
library(devtools)
library(presto)
library(DoubletFinder)
library(Matrix)


#if (!requireNamespace("remotes", quietly = TRUE)) {
  #install.packages("remotes")
##remotes::install_github("mojaveazure/seurat-disk")
#devtools::install_github('immunogenomics/presto')
#install.packages("remotes")
#remotes::install_github("chris-mcginnis-ucsf/DoubletFinder")
setwd("/Users/sanketh/Desktop/proj1_tet_dnmt3a_mut/data/week30/anndata/")
getwd()
#Set the data dir to week 30 
dataDir <- ("/Users/sanketh/Desktop/proj1_tet_dnmt3a_mut/data/week30/")
rdaDir <- ("/Users/sanketh/Desktop/proj1_tet_dnmt3a_mut/data/week30/rda/")
```

```{r}
load(file = paste0(rdaDir,"merged_seurat_harmony.rda"))
```


#Checking the UMAP 
```{r}
DimPlot(merged_seurat_harmony, reduction = "umap", label = TRUE)
```



# Write matrix data (gene expression counts)
```{r}
counts_matrix <- GetAssayData(merged_seurat_harmony, assay = "RNA", layer = "counts")
writeMM(counts_matrix, file = "./data/week30/anndata/matrix.mtx")
```

# Write dimensional reduction matrix (PCA)
```{r}
write.csv(merged_seurat_harmony@reductions$pca@cell.embeddings,
          file = "./data/week30/anndata/pca.csv", quote = F, row.names = F)
```

For now writing only PCA, but if required write in umap and harmony as well for embedings. 


# Write gene names 
```{r}
write.table(data.frame('gene'=rownames(counts_matrix)),
            file = "./data/week30/anndata/gene_names.csv",
            quote = F, row.names = F, col.names = T)
test <- read_csv(file = "./data/week30/anndata/gene_names.csv", show_col_types = F)
```

# Save the metadata table 
```{r}
merged_seurat_harmony$barcode <- colnames(merged_seurat_harmony)
merged_seurat_harmony$UMAP_1 <- merged_seurat_harmony@reductions$umap@cell.embeddings[,1]
merged_seurat_harmony$UMAP_2 <- merged_seurat_harmony@reductions$umap@cell.embeddings[,2]
merged_seurat_harmony$harmony_1 <- merged_seurat_harmony@reductions$harmony@cell.embeddings[,1]
merged_seurat_harmony$harmony_2 <- merged_seurat_harmony@reductions$harmony@cell.embeddings[,2]
write.csv(merged_seurat_harmony@meta.data, file = "./data/week30/anndata/metadata.csv",
          quote = F, row.names = F)
```














